name: github_search
description: "A new Flutter project."
publish_to: 'none' # Remove this line if you wish to publish to pub.dev

version: 1.0.0+1

environment:
  sdk: '>=3.3.3 <4.0.0'

dependencies:
  bloc: ^8.1.4
  cupertino_icons: ^1.0.6
  equatable: ^2.0.5
  flutter:
    sdk: flutter
  flutter_bloc: ^8.1.1
  flutter_localizations:
    sdk: flutter
  flutter_svg: ^2.0.10+1
  freezed: ^2.3.2
  freezed_annotation: ^2.2.0
  http: ^1.2.1
  intl: ^0.18.1
  meta: ^1.11.0
  shared_preferences: ^2.2.3
  url_launcher: ^6.2.6

dev_dependencies:
  build_runner: ^2.3.3
  flutter_lints: ^3.0.0
  flutter_test:
    sdk: flutter

flutter:
  generate: true
  uses-material-design: true
  assets:
    - assets/images/
    - assets/icons/
    - assets/icons/svg/
    - assets/icons/png/
  # fonts:
  #   - family: Schyler
  #     fonts:
  #       - asset: fonts/Schyler-Regular.ttf
  #       - asset: fonts/Schyler-Italic.ttf
  #         style: italic
  #   - family: Trajan Pro
  #     fonts:
  #       - asset: fonts/TrajanPro.ttf
  #       - asset: fonts/TrajanPro_Bold.ttf
  #         weight: 700
